# This job is for running one cron job or a subset of cron job
# It runs all jobs under jobs/daily folder daily
name: Report Time

# Controls when the workflow will run
on:
  # Triggers the workflow on push to test branch or cron job
  push:
    branches: [ develop ]
  schedule:
    - cron:  '0 0 * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run the main crawler
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FROM_EMAIL_ADDRESS: ${{ secrets.FROM_EMAIL_ADDRESS }}
          TO_EMAIL_ADDRESS: ${{ secrets.TO_EMAIL_ADDRESS }}
        run: python run.py --modules ./jobs/daily
          
